version: '3.7'

services:

  mongodb_node1:
    image: mongo:latest
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    networks:
      - mongodb-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret

  mongodb_node2:
    image: mongo:latest
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    depends_on:
      - mongodb_node1
    networks:
      - mongodb-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret

  mongodb_node3:
    image: mongo:latest
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    depends_on:
      - mongodb_node1
    networks:
      - mongodb-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret

  benchmark01:
    image: ycsb:0.17.0
    build: ./ycsb/
    hostname: benchmark01
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 81M
    networks:
      - mongodb-network
    depends_on:
      - mongodb_node1
      - mongodb_node2
      - mongodb_node3
    environment:
      - MONGO_NODES=mongodb_node1,mongodb_node2,mongodb_node3
      - MONGO_PORT=27017
    volumes:
      - ./ycsb/db.properties:/app/ycsb-0.18.0/db.properties
      - ./ycsb/replica01.properties:/app/ycsb-0.18.0/replica.properties
      - ./ycsb/results:/results

  benchmark02:
    image: ycsb:0.17.0
    build: ./ycsb/
    hostname: benchmark02
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 81M
    networks:
      - mongodb-network
    depends_on:
      - mongodb_node1
      - mongodb_node2
      - mongodb_node3
    environment:
      - MONGO_NODES=mongodb_node1,mongodb_node2,mongodb_node3
      - MONGO_PORT=27017
    volumes:
      - ./ycsb/db.properties:/app/ycsb-0.18.0/db.properties
      - ./ycsb/replica02.properties:/app/ycsb-0.18.0/replica.properties
      - ./ycsb/results:/results

  benchmark03:
    image: ycsb:0.17.0
    build: ./ycsb/
    hostname: benchmark03
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 81M
    networks:
      - mongodb-network
    depends_on:
      - mongodb_node1
      - mongodb_node2
      - mongodb_node3
    environment:
      - MONGO_NODES=mongodb_node1,mongodb_node2,mongodb_node3
      - MONGO_PORT=27017
    volumes:
      - ./ycsb/db.properties:/app/ycsb-0.18.0/db.properties
      - ./ycsb/replica03.properties:/app/ycsb-0.18.0/replica.properties
      - ./ycsb/results:/results

networks:
  mongodb-network:
